apiVersion: v1
kind: Service
metadata:
  name: "demo-test-service"
  namespace: "demo-project-test"
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: NodePort
  selector:
    app: "demo"