apiVersion: v1
kind: Ingress
metadata:
  name: "demo-ingress"
  namespace: "demo-project"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: demo-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "service-demo"
              servicePort: 80