apiVersion: v1
kind: Service
metadata:
  name: "service-demo"
  namespace: "demo-project"
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: NodePort
  selector:
    app: "demo"