apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "pythondemo-ingress"
  namespace: "pythondemo"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  labels:
    app: pythondemo-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pythondemo
            port:
              number: 8080