apiVersion: apps/v1
kind: Deployment
metadata:
  name: "pythondemo-deployment"
  namespace: "pythondemo"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demoproject
  template:
    metadata:
      labels:
        app: "demoproject"
    spec:
      containers:
      - image: 359747720927.dkr.ecr.us-east-1.amazonaws.com/demoproject:28
        imagePullPolicy: Always
        name: "pythondemo"
        ports:
        - containerPort: 8080
