apiVersion: v1
kind: Service
metadata:
  name: "service-pythondemo"
  namespace: "pythondemo"
#  annotations:

spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app: "pythondemo"